# Generated by Django 6.0.4 on 2026-05-03 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='vendor',
            new_name='vendor_user',
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hub.jobpost'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor (Company)'), ('worker', 'Worker (Job Seeker)')], default='worker', max_length=10),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('managed_jobs', models.ManyToManyField(blank=True, related_name='assigned_vendors', to='hub.jobpost')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
