# Generated by Django 6.0.4 on 2026-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_rename_vendor_jobpost_vendor_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.CharField(default='Farukhnagar', max_length=255),
        ),
    ]
