# Generated by Django 6.0.4 on 2026-05-03 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_workerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='worker_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='worker_phone',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
