# Generated by Django 6.0.4 on 2026-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_application_worker_name_application_worker_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='user_type',
            field=models.CharField(choices=[('worker', 'Worker'), ('vendor', 'Vendor')], default='worker', max_length=10),
        ),
    ]
