# Generated by Django 6.0.4 on 2026-05-04 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_workerprofile_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerprofile',
            old_name='identity_verified',
            new_name='is_aadhar_verified',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='e.g. Scanning, Driving, Forklift', max_length=255),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='verified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_category',
            field=models.CharField(default='Logistics', max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='work_history',
            field=models.TextField(blank=True, help_text='Pichli companies aur roles ki detail'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
