# Generated by Django 6.0.4 on 2026-05-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_rename_identity_verified_workerprofile_is_aadhar_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g. Expert Picker with 2+ years at Flipkart', max_length=150),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_summary',
            field=models.TextField(help_text='Brief summary of your work'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Separate skills with commas, e.g. Scanning, Driving', max_length=255),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='work_history',
            field=models.TextField(blank=True, help_text='Detailed past company roles'),
        ),
    ]
