# Generated by Django 6.0.4 on 2026-05-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0010_workerprofile_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='worker_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='worker_phone',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=20),
        ),
    ]
