# Generated by Django 6.0.4 on 2026-05-06 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_message_file_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='job_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
