# Generated by Django 6.0.4 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0014_jobpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
