# Generated by Django 6.0.4 on 2026-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0015_workerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Example: MS Office Certificate, Heavy Driving License', null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Example: Data Entry, Driving, Tally', null=True),
        ),
    ]
