# Generated by Django 6.0.4 on 2026-05-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='chat_docs/'),
        ),
    ]
