# Generated by Django 6.0.4 on 2026-05-10 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0018_message_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='managed_jobs',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(default='Not Provided', help_text='Full warehouse/office address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_person',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True, help_text='About your logistics company'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Example: Heavy Driving License', null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_summary',
            field=models.TextField(blank=True, help_text='Brief summary of your work'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Example: Scanning, Driving, Tally', null=True),
        ),
    ]
