# Generated by Django 6.0.4 on 2026-05-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_remove_vendorprofile_managed_jobs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='expected_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='last_company',
            field=models.CharField(blank=True, help_text='Last company details', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='location',
            field=models.CharField(default='Farukhnagar', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='total_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='experience_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='headline',
            field=models.CharField(blank=True, help_text='e.g. Expert Picker with 2+ years experience', max_length=150),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='work_history',
            field=models.TextField(blank=True),
        ),
    ]
