# Generated by Django 6.0.4 on 2026-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='last_company',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
