# Generated by Django 6.0.4 on 2026-05-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0024_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='worker',
            new_name='worker_profile',
        ),
        migrations.AddField(
            model_name='comment',
            name='worker_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.workerprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'worker_profile')},
        ),
    ]
