# Generated by Django 6.0.4 on 2026-05-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_rename_worker_like_worker_profile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='worker_profile',
            new_name='worker',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hub.jobpost'),
        ),
    ]
