# Generated by Django 6.0.4 on 2026-06-04 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_rename_worker_profile_comment_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.workerprofile'),
        ),
    ]
