# Generated by Django 6.0.4 on 2026-06-04 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0027_alter_comment_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='hub.jobpost'),
        ),
    ]
