# Generated by Django 6.0.4 on 2026-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0031_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
