# Generated by Django 6.0.4 on 2026-06-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0033_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
