# Generated by Django 6.0.4 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0034_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='about',
            field=models.TextField(blank=True, help_text='Apne baare mein thoda likhein...', null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='industry',
            field=models.CharField(default='Logistics', max_length=100),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='worker_banners/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
