# Generated by Django 6.0.4 on 2026-06-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0035_workerprofile_about_workerprofile_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
