# Generated by Django 6.0.4 on 2026-07-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0036_jobpost_featured_until_jobpost_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='about_us',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='company_size',
            field=models.CharField(choices=[('1-10', '1-10 Employees'), ('11-50', '11-50 Employees'), ('50+', '50+ Employees')], default='1-10', max_length=50),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
