# Generated by Django 6.0.4 on 2026-07-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0037_vendorprofile_about_us_vendorprofile_company_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='required_skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
