# Generated by Django 6.0.4 on 2026-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0038_jobpost_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
