# Generated by Django 6.0.4 on 2026-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0040_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
