# Generated by Django 6.0.4 on 2026-07-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0043_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='workers/images/'),
        ),
    ]
