# Generated by Django 6.0.4 on 2026-07-17 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models  # Yeh line zaroori hai

class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0046_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(
                null=True, 
                blank=True, 
                default=None, 
                on_delete=django.db.models.deletion.CASCADE, 
                related_name='owned_groups', 
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]