# Generated by Django 6.0.4 on 2026-07-18 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0048_alter_group_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_domain',
            field=models.CharField(blank=True, help_text='e.g. flipkart.com', max_length=100, null=True),
        ),
    ]
