# Generated by Django 6.0.4 on 2026-07-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0049_jobpost_company_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='company_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
