# Generated by Django 6.0.4 on 2026-07-23 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0050_alter_jobpost_company_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
